struct v__Infer <: v end
struct v__Skip <: v end
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Chain_Parametric_Type/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Chain_Parametric_Value/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Chain_Parametric_Value_Sparse/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Chain_Unparametric/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Cat_Parametric_Type/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Cat_Parametric_Value/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Cat_Parametric_Value_Sparse/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Cat_Unparametric/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Convolution_Parametric_Type/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Convolution_Parametric_Value/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Convolution_Parametric_Value_Sparse/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Convolution_Unparametric/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Convolution_Parametric_Wrapper/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("MaxPool_Parametric_Type/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("MaxPool_Parametric_Wrapper/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("MaxPool_Unparametric/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Nop_Unparametric/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Nop_Parametric_Wrapper/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Upsample_Parametric_Type/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Upsample_Parametric_Wrapper/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Upsample_Parametric_Value/'Value'1.jl")))
include!(SoftLux, @c__URI(SoftBase.Directory, a__Path("Upsample_Unparametric/'Value'1.jl")))